// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileapplication.proxies;

public class ProductFeatureImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MobileApplication.ProductFeatureImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		crtd_dte("crtd_dte"),
		Chngd_dte("Chngd_dte"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ProductFeatureImage_Product("MobileApplication.ProductFeatureImage_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductFeatureImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MobileApplication.ProductFeatureImage"));
	}

	protected ProductFeatureImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productFeatureImageMendixObject)
	{
		super(context, productFeatureImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MobileApplication.ProductFeatureImage", productFeatureImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MobileApplication.ProductFeatureImage");
	}

	/**
	 * @deprecated Use 'ProductFeatureImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mobileapplication.proxies.ProductFeatureImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mobileapplication.proxies.ProductFeatureImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mobileapplication.proxies.ProductFeatureImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mobileapplication.proxies.ProductFeatureImage(context, mendixObject);
	}

	public static mobileapplication.proxies.ProductFeatureImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mobileapplication.proxies.ProductFeatureImage.initialize(context, mendixObject);
	}

	public static java.util.List<mobileapplication.proxies.ProductFeatureImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mobileapplication.proxies.ProductFeatureImage> result = new java.util.ArrayList<mobileapplication.proxies.ProductFeatureImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MobileApplication.ProductFeatureImage" + xpathConstraint))
			result.add(mobileapplication.proxies.ProductFeatureImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of crtd_dte
	 */
	public final java.util.Date getcrtd_dte()
	{
		return getcrtd_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of crtd_dte
	 */
	public final java.util.Date getcrtd_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.crtd_dte.toString());
	}

	/**
	 * Set value of crtd_dte
	 * @param crtd_dte
	 */
	public final void setcrtd_dte(java.util.Date crtd_dte)
	{
		setcrtd_dte(getContext(), crtd_dte);
	}

	/**
	 * Set value of crtd_dte
	 * @param context
	 * @param crtd_dte
	 */
	public final void setcrtd_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date crtd_dte)
	{
		getMendixObject().setValue(context, MemberNames.crtd_dte.toString(), crtd_dte);
	}

	/**
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte()
	{
		return getChngd_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Chngd_dte.toString());
	}

	/**
	 * Set value of Chngd_dte
	 * @param chngd_dte
	 */
	public final void setChngd_dte(java.util.Date chngd_dte)
	{
		setChngd_dte(getContext(), chngd_dte);
	}

	/**
	 * Set value of Chngd_dte
	 * @param context
	 * @param chngd_dte
	 */
	public final void setChngd_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date chngd_dte)
	{
		getMendixObject().setValue(context, MemberNames.Chngd_dte.toString(), chngd_dte);
	}

	/**
	 * @return value of ProductFeatureImage_Product
	 */
	public final mobileapplication.proxies.Product getProductFeatureImage_Product() throws com.mendix.core.CoreException
	{
		return getProductFeatureImage_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductFeatureImage_Product
	 */
	public final mobileapplication.proxies.Product getProductFeatureImage_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mobileapplication.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductFeatureImage_Product.toString());
		if (identifier != null)
			result = mobileapplication.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductFeatureImage_Product
	 * @param productfeatureimage_product
	 */
	public final void setProductFeatureImage_Product(mobileapplication.proxies.Product productfeatureimage_product)
	{
		setProductFeatureImage_Product(getContext(), productfeatureimage_product);
	}

	/**
	 * Set value of ProductFeatureImage_Product
	 * @param context
	 * @param productfeatureimage_product
	 */
	public final void setProductFeatureImage_Product(com.mendix.systemwideinterfaces.core.IContext context, mobileapplication.proxies.Product productfeatureimage_product)
	{
		if (productfeatureimage_product == null)
			getMendixObject().setValue(context, MemberNames.ProductFeatureImage_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductFeatureImage_Product.toString(), productfeatureimage_product.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobileapplication.proxies.ProductFeatureImage that = (mobileapplication.proxies.ProductFeatureImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MobileApplication.ProductFeatureImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
