// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileapplication.proxies;

public class ProductBannerImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MobileApplication.ProductBannerImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileName("FileName"),
		Creatd_dte("Creatd_dte"),
		Chngd_dte("Chngd_dte"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ProductBannerImage_Product("MobileApplication.ProductBannerImage_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductBannerImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MobileApplication.ProductBannerImage"));
	}

	protected ProductBannerImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productBannerImageMendixObject)
	{
		super(context, productBannerImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MobileApplication.ProductBannerImage", productBannerImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MobileApplication.ProductBannerImage");
	}

	/**
	 * @deprecated Use 'ProductBannerImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mobileapplication.proxies.ProductBannerImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mobileapplication.proxies.ProductBannerImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mobileapplication.proxies.ProductBannerImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mobileapplication.proxies.ProductBannerImage(context, mendixObject);
	}

	public static mobileapplication.proxies.ProductBannerImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mobileapplication.proxies.ProductBannerImage.initialize(context, mendixObject);
	}

	public static java.util.List<mobileapplication.proxies.ProductBannerImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mobileapplication.proxies.ProductBannerImage> result = new java.util.ArrayList<mobileapplication.proxies.ProductBannerImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MobileApplication.ProductBannerImage" + xpathConstraint))
			result.add(mobileapplication.proxies.ProductBannerImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FileName
	 */
	public final java.lang.String getFileName()
	{
		return getFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of FileName
	 */
	public final java.lang.String getFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileName.toString());
	}

	/**
	 * Set value of FileName
	 * @param filename
	 */
	public final void setFileName(java.lang.String filename)
	{
		setFileName(getContext(), filename);
	}

	/**
	 * Set value of FileName
	 * @param context
	 * @param filename
	 */
	public final void setFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.FileName.toString(), filename);
	}

	/**
	 * @return value of Creatd_dte
	 */
	public final java.util.Date getCreatd_dte()
	{
		return getCreatd_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of Creatd_dte
	 */
	public final java.util.Date getCreatd_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Creatd_dte.toString());
	}

	/**
	 * Set value of Creatd_dte
	 * @param creatd_dte
	 */
	public final void setCreatd_dte(java.util.Date creatd_dte)
	{
		setCreatd_dte(getContext(), creatd_dte);
	}

	/**
	 * Set value of Creatd_dte
	 * @param context
	 * @param creatd_dte
	 */
	public final void setCreatd_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date creatd_dte)
	{
		getMendixObject().setValue(context, MemberNames.Creatd_dte.toString(), creatd_dte);
	}

	/**
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte()
	{
		return getChngd_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Chngd_dte.toString());
	}

	/**
	 * Set value of Chngd_dte
	 * @param chngd_dte
	 */
	public final void setChngd_dte(java.util.Date chngd_dte)
	{
		setChngd_dte(getContext(), chngd_dte);
	}

	/**
	 * Set value of Chngd_dte
	 * @param context
	 * @param chngd_dte
	 */
	public final void setChngd_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date chngd_dte)
	{
		getMendixObject().setValue(context, MemberNames.Chngd_dte.toString(), chngd_dte);
	}

	/**
	 * @return value of ProductBannerImage_Product
	 */
	public final mobileapplication.proxies.Product getProductBannerImage_Product() throws com.mendix.core.CoreException
	{
		return getProductBannerImage_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductBannerImage_Product
	 */
	public final mobileapplication.proxies.Product getProductBannerImage_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mobileapplication.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductBannerImage_Product.toString());
		if (identifier != null)
			result = mobileapplication.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductBannerImage_Product
	 * @param productbannerimage_product
	 */
	public final void setProductBannerImage_Product(mobileapplication.proxies.Product productbannerimage_product)
	{
		setProductBannerImage_Product(getContext(), productbannerimage_product);
	}

	/**
	 * Set value of ProductBannerImage_Product
	 * @param context
	 * @param productbannerimage_product
	 */
	public final void setProductBannerImage_Product(com.mendix.systemwideinterfaces.core.IContext context, mobileapplication.proxies.Product productbannerimage_product)
	{
		if (productbannerimage_product == null)
			getMendixObject().setValue(context, MemberNames.ProductBannerImage_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductBannerImage_Product.toString(), productbannerimage_product.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobileapplication.proxies.ProductBannerImage that = (mobileapplication.proxies.ProductBannerImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MobileApplication.ProductBannerImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
