// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileapplication.proxies;

public class Product extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MobileApplication.Product";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		Feature("Feature"),
		Price("Price"),
		Quantity("Quantity"),
		Check("Check"),
		Stock("Stock"),
		TotalRedeemPoints("TotalRedeemPoints"),
		ProductID("ProductID"),
		Crt_dte("Crt_dte"),
		Chngd_dte("Chngd_dte"),
		ImageString("ImageString"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ProductBannerImage_Product("MobileApplication.ProductBannerImage_Product"),
		Redeem_Product("MobileApplication.Redeem_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Product(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MobileApplication.Product"));
	}

	protected Product(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productMendixObject)
	{
		super(context, productMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MobileApplication.Product", productMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MobileApplication.Product");
	}

	/**
	 * @deprecated Use 'Product.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mobileapplication.proxies.Product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mobileapplication.proxies.Product.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mobileapplication.proxies.Product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mobileapplication.proxies.Product(context, mendixObject);
	}

	public static mobileapplication.proxies.Product load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mobileapplication.proxies.Product.initialize(context, mendixObject);
	}

	public static java.util.List<mobileapplication.proxies.Product> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mobileapplication.proxies.Product> result = new java.util.ArrayList<mobileapplication.proxies.Product>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MobileApplication.Product" + xpathConstraint))
			result.add(mobileapplication.proxies.Product.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Feature
	 */
	public final java.lang.String getFeature()
	{
		return getFeature(getContext());
	}

	/**
	 * @param context
	 * @return value of Feature
	 */
	public final java.lang.String getFeature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Feature.toString());
	}

	/**
	 * Set value of Feature
	 * @param feature
	 */
	public final void setFeature(java.lang.String feature)
	{
		setFeature(getContext(), feature);
	}

	/**
	 * Set value of Feature
	 * @param context
	 * @param feature
	 */
	public final void setFeature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String feature)
	{
		getMendixObject().setValue(context, MemberNames.Feature.toString(), feature);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of Check
	 */
	public final java.lang.Boolean getCheck()
	{
		return getCheck(getContext());
	}

	/**
	 * @param context
	 * @return value of Check
	 */
	public final java.lang.Boolean getCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Check.toString());
	}

	/**
	 * Set value of Check
	 * @param check
	 */
	public final void setCheck(java.lang.Boolean check)
	{
		setCheck(getContext(), check);
	}

	/**
	 * Set value of Check
	 * @param context
	 * @param check
	 */
	public final void setCheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean check)
	{
		getMendixObject().setValue(context, MemberNames.Check.toString(), check);
	}

	/**
	 * @return value of Stock
	 */
	public final java.lang.Integer getStock()
	{
		return getStock(getContext());
	}

	/**
	 * @param context
	 * @return value of Stock
	 */
	public final java.lang.Integer getStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Stock.toString());
	}

	/**
	 * Set value of Stock
	 * @param stock
	 */
	public final void setStock(java.lang.Integer stock)
	{
		setStock(getContext(), stock);
	}

	/**
	 * Set value of Stock
	 * @param context
	 * @param stock
	 */
	public final void setStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer stock)
	{
		getMendixObject().setValue(context, MemberNames.Stock.toString(), stock);
	}

	/**
	 * @return value of TotalRedeemPoints
	 */
	public final java.lang.Integer getTotalRedeemPoints()
	{
		return getTotalRedeemPoints(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalRedeemPoints
	 */
	public final java.lang.Integer getTotalRedeemPoints(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalRedeemPoints.toString());
	}

	/**
	 * Set value of TotalRedeemPoints
	 * @param totalredeempoints
	 */
	public final void setTotalRedeemPoints(java.lang.Integer totalredeempoints)
	{
		setTotalRedeemPoints(getContext(), totalredeempoints);
	}

	/**
	 * Set value of TotalRedeemPoints
	 * @param context
	 * @param totalredeempoints
	 */
	public final void setTotalRedeemPoints(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalredeempoints)
	{
		getMendixObject().setValue(context, MemberNames.TotalRedeemPoints.toString(), totalredeempoints);
	}

	/**
	 * @return value of ProductID
	 */
	public final java.lang.Long getProductID()
	{
		return getProductID(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductID
	 */
	public final java.lang.Long getProductID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ProductID.toString());
	}

	/**
	 * Set value of ProductID
	 * @param productid
	 */
	public final void setProductID(java.lang.Long productid)
	{
		setProductID(getContext(), productid);
	}

	/**
	 * Set value of ProductID
	 * @param context
	 * @param productid
	 */
	public final void setProductID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long productid)
	{
		getMendixObject().setValue(context, MemberNames.ProductID.toString(), productid);
	}

	/**
	 * @return value of Crt_dte
	 */
	public final java.util.Date getCrt_dte()
	{
		return getCrt_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of Crt_dte
	 */
	public final java.util.Date getCrt_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Crt_dte.toString());
	}

	/**
	 * Set value of Crt_dte
	 * @param crt_dte
	 */
	public final void setCrt_dte(java.util.Date crt_dte)
	{
		setCrt_dte(getContext(), crt_dte);
	}

	/**
	 * Set value of Crt_dte
	 * @param context
	 * @param crt_dte
	 */
	public final void setCrt_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date crt_dte)
	{
		getMendixObject().setValue(context, MemberNames.Crt_dte.toString(), crt_dte);
	}

	/**
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte()
	{
		return getChngd_dte(getContext());
	}

	/**
	 * @param context
	 * @return value of Chngd_dte
	 */
	public final java.util.Date getChngd_dte(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Chngd_dte.toString());
	}

	/**
	 * Set value of Chngd_dte
	 * @param chngd_dte
	 */
	public final void setChngd_dte(java.util.Date chngd_dte)
	{
		setChngd_dte(getContext(), chngd_dte);
	}

	/**
	 * Set value of Chngd_dte
	 * @param context
	 * @param chngd_dte
	 */
	public final void setChngd_dte(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date chngd_dte)
	{
		getMendixObject().setValue(context, MemberNames.Chngd_dte.toString(), chngd_dte);
	}

	/**
	 * @return value of ImageString
	 */
	public final java.lang.String getImageString()
	{
		return getImageString(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageString
	 */
	public final java.lang.String getImageString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageString.toString());
	}

	/**
	 * Set value of ImageString
	 * @param imagestring
	 */
	public final void setImageString(java.lang.String imagestring)
	{
		setImageString(getContext(), imagestring);
	}

	/**
	 * Set value of ImageString
	 * @param context
	 * @param imagestring
	 */
	public final void setImageString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagestring)
	{
		getMendixObject().setValue(context, MemberNames.ImageString.toString(), imagestring);
	}

	/**
	 * @return value of ProductBannerImage_Product
	 */
	public final mobileapplication.proxies.ProductBannerImage getProductBannerImage_Product() throws com.mendix.core.CoreException
	{
		return getProductBannerImage_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductBannerImage_Product
	 */
	public final mobileapplication.proxies.ProductBannerImage getProductBannerImage_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mobileapplication.proxies.ProductBannerImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductBannerImage_Product.toString());
		if (identifier != null)
			result = mobileapplication.proxies.ProductBannerImage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductBannerImage_Product
	 * @param productbannerimage_product
	 */
	public final void setProductBannerImage_Product(mobileapplication.proxies.ProductBannerImage productbannerimage_product)
	{
		setProductBannerImage_Product(getContext(), productbannerimage_product);
	}

	/**
	 * Set value of ProductBannerImage_Product
	 * @param context
	 * @param productbannerimage_product
	 */
	public final void setProductBannerImage_Product(com.mendix.systemwideinterfaces.core.IContext context, mobileapplication.proxies.ProductBannerImage productbannerimage_product)
	{
		if (productbannerimage_product == null)
			getMendixObject().setValue(context, MemberNames.ProductBannerImage_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductBannerImage_Product.toString(), productbannerimage_product.getMendixObject().getId());
	}

	/**
	 * @return value of Redeem_Product
	 */
	public final mobileapplication.proxies.Redeem getRedeem_Product() throws com.mendix.core.CoreException
	{
		return getRedeem_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of Redeem_Product
	 */
	public final mobileapplication.proxies.Redeem getRedeem_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mobileapplication.proxies.Redeem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Redeem_Product.toString());
		if (identifier != null)
			result = mobileapplication.proxies.Redeem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Redeem_Product
	 * @param redeem_product
	 */
	public final void setRedeem_Product(mobileapplication.proxies.Redeem redeem_product)
	{
		setRedeem_Product(getContext(), redeem_product);
	}

	/**
	 * Set value of Redeem_Product
	 * @param context
	 * @param redeem_product
	 */
	public final void setRedeem_Product(com.mendix.systemwideinterfaces.core.IContext context, mobileapplication.proxies.Redeem redeem_product)
	{
		if (redeem_product == null)
			getMendixObject().setValue(context, MemberNames.Redeem_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Redeem_Product.toString(), redeem_product.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobileapplication.proxies.Product that = (mobileapplication.proxies.Product) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MobileApplication.Product";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
