// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileapplication.proxies;

public class PurchasedProducts
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject purchasedProductsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MobileApplication.PurchasedProducts";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Price("Price"),
		Quantity("Quantity"),
		UserID("UserID"),
		PurchasedProducts_Product("MobileApplication.PurchasedProducts_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PurchasedProducts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MobileApplication.PurchasedProducts"));
	}

	protected PurchasedProducts(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject purchasedProductsMendixObject)
	{
		if (purchasedProductsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MobileApplication.PurchasedProducts", purchasedProductsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MobileApplication.PurchasedProducts");

		this.purchasedProductsMendixObject = purchasedProductsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PurchasedProducts.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mobileapplication.proxies.PurchasedProducts initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mobileapplication.proxies.PurchasedProducts.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mobileapplication.proxies.PurchasedProducts initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mobileapplication.proxies.PurchasedProducts(context, mendixObject);
	}

	public static mobileapplication.proxies.PurchasedProducts load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mobileapplication.proxies.PurchasedProducts.initialize(context, mendixObject);
	}

	public static java.util.List<mobileapplication.proxies.PurchasedProducts> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mobileapplication.proxies.PurchasedProducts> result = new java.util.ArrayList<mobileapplication.proxies.PurchasedProducts>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MobileApplication.PurchasedProducts" + xpathConstraint))
			result.add(mobileapplication.proxies.PurchasedProducts.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of UserID
	 */
	public final java.lang.String getUserID()
	{
		return getUserID(getContext());
	}

	/**
	 * @param context
	 * @return value of UserID
	 */
	public final java.lang.String getUserID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserID.toString());
	}

	/**
	 * Set value of UserID
	 * @param userid
	 */
	public final void setUserID(java.lang.String userid)
	{
		setUserID(getContext(), userid);
	}

	/**
	 * Set value of UserID
	 * @param context
	 * @param userid
	 */
	public final void setUserID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userid)
	{
		getMendixObject().setValue(context, MemberNames.UserID.toString(), userid);
	}

	/**
	 * @return value of PurchasedProducts_Product
	 */
	public final java.util.List<mobileapplication.proxies.Product> getPurchasedProducts_Product() throws com.mendix.core.CoreException
	{
		return getPurchasedProducts_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of PurchasedProducts_Product
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mobileapplication.proxies.Product> getPurchasedProducts_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mobileapplication.proxies.Product> result = new java.util.ArrayList<mobileapplication.proxies.Product>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PurchasedProducts_Product.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mobileapplication.proxies.Product.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of PurchasedProducts_Product
	 * @param purchasedproducts_product
	 */
	public final void setPurchasedProducts_Product(java.util.List<mobileapplication.proxies.Product> purchasedproducts_product)
	{
		setPurchasedProducts_Product(getContext(), purchasedproducts_product);
	}

	/**
	 * Set value of PurchasedProducts_Product
	 * @param context
	 * @param purchasedproducts_product
	 */
	public final void setPurchasedProducts_Product(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mobileapplication.proxies.Product> purchasedproducts_product)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mobileapplication.proxies.Product proxyObject : purchasedproducts_product)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.PurchasedProducts_Product.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return purchasedProductsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobileapplication.proxies.PurchasedProducts that = (mobileapplication.proxies.PurchasedProducts) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MobileApplication.PurchasedProducts";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
