// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileapplication.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MobileApplication module
	public static void aCT_AddToCart(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_AddToCart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_BuyPopUp(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_BuyPopUp", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static administration.proxies.Account aCT_GetCurrentAccount(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MobileApplication.ACT_GetCurrentAccount", params);
			return result == null ? null : administration.proxies.Account.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_My_Cart_Buy(IContext context, mobileapplication.proxies.MyCart _myCart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MyCart", _myCart == null ? null : _myCart.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_My_Cart_Buy", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_Procedd_To_Buy(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_Procedd_To_Buy", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_Redeem_Pop_Up(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_Redeem_Pop_Up", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_Redeem_Save(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.ACT_Redeem_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void buyPopUp_Save(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.BuyPopUp_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Delete_ExistingData(IContext context, mobileapplication.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MobileApplication.IVK_Delete_ExistingData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Get_Data_Web(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MobileApplication.IVK_Get_Data_Web", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mobileapplication.proxies.Product> iVK_Get_Data_Web_2(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "MobileApplication.IVK_Get_Data_Web_2", params);
			java.util.List<mobileapplication.proxies.Product> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mobileapplication.proxies.Product>();
				for (IMendixObject obj : objs)
					result.add(mobileapplication.proxies.Product.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Get_Data_Web_3(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MobileApplication.IVK_Get_Data_Web_3", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}